#ifndef GUARD_CONSTANTS_BATTLE_TRANSITION_H
#define GUARD_CONSTANTS_BATTLE_TRANSITION_H

#define MUGSHOT_SIDNEY      0
#define MUGSHOT_PHOEBE      1
#define MUGSHOT_GLACIA      2
#define MUGSHOT_DRAKE       3
#define MUGSHOT_CHAMPION    4
#define MUGSHOT_REMI        5
#define MUGSHOT_DECLAN      6
#define MUGSHOT_RITA        7
#define MUGSHOT_MIRAGE      8
#define MUGSHOT_ADAMINA     9
#define MUGSHOT_JAKE        10
#define MUGSHOT_KAIZEN1     11
#define MUGSHOT_KAIZEN2     12
#define MUGSHOT_SOPHIA      13
#define MUGSHOT_ODYSSEUS    14
#define MUGSHOT_JULIE       15
#define MUGSHOT_PAM_AND_CAM 16
#define MUGSHOT_MIRAGES     17
#define MUGSHOT_COREY       18
#define MUGSHOT_JOEY        19
#define MUGSHOT_PHILLIPA    20
#define MUGSHOT_ISABELLA    21
#define MUGSHOT_BETTY       22
#define MUGSHOT_MINA        23
#define MUGSHOT_NEWTON      24
#define MUGSHOT_JENNY       25
#define MUGSHOT_MIGUEL      26


#define MUGSHOTS_COUNT      27

#endif //GUARD_CONSTANTS_BATTLE_TRANSITION_H