gText_Quentin_EndofDemo:
	.string "{COLOR BLUE}Quentin{COLOR DARK_GREY}: THIS IS THE END OF THE\n"
	.string "DEMO. THE ARCHITECT, {COLOR BLUE}EATTHEPEAR{COLOR DARK_GREY}, IS\l"
	.string "STILL WORKING ON THE REMAINDER OF\l"
	.string "THE {COLOR RED}BATTLE LABYRINTH{COLOR DARK_GREY}.\p"
	.string "PLEASE SAVE YOUR GAME USING THE IN\n"
	.string "GAME SAVE SO YOU CAN TRANSFER YOUR\l"
	.string "SAVE FILE TO THE NEXT VERSION\l"
	.string "WHEN IT COMES OUT.$"

gText_Quentin_Rules:
	.string "THE BATTLE LABYRINTH IS COMPRISED\n"
	.string "OF MANY ZONES YOU MUST TRAVERSE.\p"
	.string "IN THESE ZONES, YOU MIGHT ENCOUNTER\n"
	.string "WILD POKEMON, GREAT TREASURES,\l"
	.string "TOUGH TRAINERS, AND MORE.\p"
	.string "AT THE END OF EACH ZONE AND BEFORE\n"
	.string "THE NEXT BEGINS, YOU WILL FIND\l"
	.string "A SANCTUARY, LIKE THIS ONE, WITH\l"
	.string "SHOPS TO PURCHASE SUPPLIES, HEAL\l"
	.string "YOUR POKEMON, AND OTHER BENEFITS.\p"
	.string "ONCE YOU ENTER A NEW ZONE,\n"
	.string "YOU WILL NOT BE ABLE TO RETURN TO\l"
	.string "THE SANCTUARY, NOR ANY PRIOR ZONES.$"

gText_Quentin_DontLose:
	.string "{COLOR BLUE}Quentin{COLOR DARK_GREY}: YOU MUST PROGRESS THROUGH\n"
	.string "ALL ZONES WITHOUT LOSING A BATTLE,\l"
	.string "WHICH WOULD RESULT IN AN AUTOMATIC\l"
	.string "RESTART OF THE SIMULATION.$"

gText_Quentin_Onwards:
	.string "{COLOR BLUE}Quentin{COLOR DARK_GREY}: ONWARDS, TO VICTORY!$"

gText_Quentin_Unlocked:
	.string "{COLOR BLUE}Quentin{COLOR DARK_GREY}: BECAUSE OF YOUR PROGRESS,\p"
	.string "THE FOLLOWING SHOPS ARE UPGRADED:$"

gText_Quentin_UnlockedGeneral:
	.string "TIM'S GENERAL PURPOSE SHOP.$"

gText_Quentin_UnlockedUnique:
	.string "SILPH UNIQUE ITEM SHOP.$"

gText_Quentin_UnlockedServices:
	.string "LELOUCH'S SPECIAL SERVICES SHOP.$"

gText_GeneralSign:
	.string "Tim's General Purpose Shop\n"
	.string "Sponsored by Pokémart Inc.$"

gText_Tim_Intro:
	.string "{COLOR BLUE}???{COLOR DARK_GREY}: New challenger, huh?\n"
	.string "The name's Tim Johnson.\p"
	.string "{COLOR BLUE}Tim{COLOR DARK_GREY}: I run this store, sponsored by\n"
	.string "Pokémart Incorporated.\l"
	.string "You can find all sorts of general\l"
	.string "supplies for your travels.$"

gText_Tim_Welcome:
	.string "{COLOR BLUE}Tim{COLOR DARK_GREY}: Welcome to Tim's.\n"
	.string "Can I get you anything?$"

gText_Tim_Leave:
	.string "{COLOR BLUE}Tim{COLOR DARK_GREY}: Have a nice day.$"

gText_UniqueSign:
	.string "Silph Unique Item Shop\n"
	.string "Need something? We probably got it!$"

gText_Varrick_Intro:
	.string "{COLOR BLUE}???{COLOR DARK_GREY}: Wowza! Yeetastic! Blamo!\p"
	.string "My name is Varrick,\n"
	.string "entrepreneur extraordinaire!\p"
	.string "{COLOR BLUE}Varrick{COLOR DARK_GREY}: I pitched this idea to\n"
	.string "Silph a couple years back,\l"
	.string "and now it's become a reality!\p"
	.string "All the random items you can't find\n"
	.string "in the world, you'll find here!\p"
	.string "Fantastic evolution stones!\p"
	.string "Countless Pokéball variations!\p"
	.string "Delicious Berries!\p"
	.string "The greatest held item collection\n"
	.string "you've never seen!\p"
	.string "Please, enjoy my shop!$"

gText_Varrick_Welcome:
	.string "{COLOR BLUE}Varrick{COLOR DARK_GREY}: Greetings and salutations!\n"
	.string "Welcome to Silph Unique Item Store!$"

gText_Varrick_Leave:
	.string "{COLOR BLUE}Varrick{COLOR DARK_GREY}: A big thank you from Silph!$"

gText_ServicesSign:
	.string "Lelouch's Special Services Shop\n"
	.string "Anything for the right price...$"

gText_Lelouch_Intro1:
	.string "{COLOR BLUE}???{COLOR DARK_GREY}: You... What is your name?\p"
	.string "{COLOR BLUE}???{COLOR DARK_GREY}: {PLAYER}? Now that's a name...\n"
	.string "I haven't heard in...$"

gText_Lelouch_Intro2:
	.string "{COLOR BLUE}???{COLOR DARK_GREY}: You may call me Lelouch.\p"
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GREY}: I provide a variety of\n"
	.string "services to improve one's Pokémon.\p"
	.string "But I demand a special price, one\n"
	.string "that I see you cannot pay.$"

gText_Lelouch_NoPoints:
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GREY}: You have nothing of value\n"
	.string "to me. Leave.$"

gText_HealingSign:
	.string "Joy's Healing Shop\n"
	.string "Health care costs money!$"

gText_Joy_CantUse:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: You can't use that without paying!$"

gText_Joy_Intro:
	.string "{COLOR BLUE}???{COLOR DARK_GREY}: Welcome to the Pokémon…\n"
	.string "Ugh. Never mind.\p"
	.string "{COLOR BLUE}???{COLOR DARK_GREY}: My name is Joy. Just Joy.\p"
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: I used to work at the\n"
	.string "Pokémon Center, but they gave\l"
	.string "terrible pay.\p"
	.string "So I've started my own shop,\n"
	.string "Joy's Healing Shop!$"

gText_Joy_Welcome:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: Welcome to Joy's Healing Shop.\p"
	.string "We heal your Pokemon for a flat\n"
	.string "¥500 fee, which also comes with\l"
	.string "access to the PC.$"

gText_Joy_Nuzlocke:
	.string "I will also remove any fallen\n"
	.string "Pokémon in your party.$"

gText_Joy_WouldYouLikeToHeal:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: Should I heal your Pokémon?$"

gText_Joy_NotEnough:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: You don't have enough money.$"

gText_Joy_ThankYou:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: That will be ¥500, thank you…$"

gText_Joy_PartyHealed:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: Your party has been restored.\n"
	.string "You can also now use the PC.$"

gText_Joy_WonderfulDay:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: Have a wonderful day!$"

gText_ExitSign:
	.string "This is the exit!\n"
	.string "If you leave, you can't come back.$"
