gText_Colress_EndofDemo:
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: This is the end of the\n"
	.string "demo. Our engineers are still\l"
	.string "working on the remainder of the\l"
	.string "{COLOR RED}Pokémon Battle Labyrinth{COLOR DARK_GRAY}.\p"
	.string "Please save your game using the in\n"
	.string "game save so you might be able to\l"
	.string "transfer your save file to the next\l"
	.string "version when it comes out.$"

gText_Colress_ReachedZone:
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: Congratulations.\n"
	.string "You have cleared {COLOR RED}Zone {STR_VAR_1}{COLOR DARK_GRAY}.$"

gText_RewardClear:
	.string "Your reward for clearing {COLOR RED}Zone {STR_VAR_1}{COLOR DARK_GRAY} is…$"

gText_Colress_WhenUReady:
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: When you are prepared to\n"
	.string "enter {COLOR RED}Zone {STR_VAR_1}{COLOR DARK_GRAY}, come speak to me.$"

gText_Colress_Greetings:
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: Greetings, {PLAYER}.\n"
	.string "What can I help you with?$"

gText_Colress_SureReadyToLeave:
	.string "{COLOR BLUE}Colress{COLOR DARK_GRAY}: Are you sure you're ready?\n"
	.string "You will be entering {COLOR RED}Zone {STR_VAR_1}{COLOR DARK_GRAY}.$"

gText_Colress_Unlocked:
	.string "Because of your progress,\p"
	.string "the following shops are upgraded:$"

gText_Colress_UnlockedGeneral:
	.string "{COLOR RED}Tim's General Purpose Shop{COLOR DARK_GRAY}!$"

gText_Colress_UnlockedUnique:
	.string "{COLOR RED}Silph Unique Item Shop{COLOR DARK_GRAY}!$"

gText_Colress_UnlockedServices:
	.string "{COLOR RED}Lelouch's Special Services Shop{COLOR DARK_GRAY}!$"

gText_Colress_UnlockedWarp:
	.string "Because of your progress,\n"
	.string "you have unlocked a special warp in\l"
	.string "Zone 0.$"

gText_Version:
	.string "This is version 1.3.1 of the\n"
	.string "Pokémon Battle Labyrinth.\p"
	.string "Make sure you're playing the\n"
	.string "most up to date version!$"

gText_GeneralSign:
	.string "Tim's General Purpose Shop\n"
	.string "Sponsored by Pokémart Inc.$"

gText_UniqueSign:
	.string "Silph Unique Item Shop\n"
	.string "Need something? We probably got it!$"

gText_ServicesSign:
	.string "Lelouch's Special Services Shop\n"
	.string "Anything for the right price…$"

gText_Lelouch_ExpTrainingFinished:
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: The training session has\n"
	.string "finished.\p"
	.string "Your Pokémon has grown stronger.$"

gText_Lelouch_DidNotTrain:
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: If you do want to\n"
	.string "train your Pokémon, I'll be here.$"

gText_Lelouch_Exp:
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: With Experience Training,\n"
	.string "you can train one Pokémon to any\l"
	.string "level up to the level cap,\l"
	.string "at the cost of one Red Shard.\p"
	.string "Would you like to start an\n"
	.string "Experience Training session?$"

gText_Lelouch_PayRed:
	.string "{PLAYER} handed over 1 Red Shard.$"

gText_Lelouch_ChooseTraining:
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Choose which training\n"
	.string "regiment you would like.$"

gText_Lelouch_CostsBlueShards:
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Move Reminder services\n"
	.string "cost one Blue Shard.\p"
	.string "Would you like me to teach a\n"
	.string "forgotten move to your Pokémon?$"

gText_Lelouch_PayBlue:
	.string "{PLAYER} handed over 1 Blue Shard.$"

gText_Lelouch_CostsYellowShards:
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: Move Tutor services cost\n"
	.string "Yellow Shards. Which move would you\l"
	.string "like to tutor?$"

gText_Lelouch_PayYellow1:
	.string "{PLAYER} handed over 1 Yellow Shard.$"

gText_Lelouch_CostsGreenShards:
	.string "{COLOR BLUE}Lelouch{COLOR DARK_GRAY}: I can craft special items\n"
	.string "as well as upgrade your items\l"
	.string "in exchange for Green Shards.\l"
	.string "What would you like?$"

gText_Lelouch_PayGreen:
	.string "{PLAYER} handed over 1 Green Shard.$"

gText_HealingSign:
	.string "Joy's Healing Shop\n"
	.string "Health care costs money!$"

gText_ExitSign:
	.string "This is the exit!$"

gText_BrutalExitNotSatisfied:
	.string "You haven't defeated all the\n"
	.string "trainers in the area yet.$"

gText_NotEnoughMons:
	.string "You need at least two Pokémon to\n"
	.string "initiate a Double Battle.$"

gText_PleasePick3Mons:
	.string "Please select three Pokémon to\n"
	.string "participate in the tag battle.$"
