gText_Quentin_Rules:
	.string "{COLOR BLUE}QUENTIN{COLOR DARK_GREY}: ALLOW ME TO GO OVER THE\n"
	.string "RULES. IN THE {COLOR RED}BATTLE LABYRINTH{COLOR DARK_GREY},\l"
	.string "THERE ARE A NUMBER OF ZONES IN\l"
	.string "WHICH YOU MUST FIND THE EXIT.\p"
	.string "IN THESE ZONES, YOU MIGHT ENCOUNTER\n"
	.string "WILD POKEMON, GREAT TREASURES,\l"
	.string "TOUGH TRAINERS, AND MORE.\p"
	.string "AT THE END OF EACH ZONE AND BEFORE\n"
	.string "THE NEXT BEGINS, YOU WILL FIND\l"
	.string "A SAFE AREA, LIKE THIS ONE, WITH\l"
	.string "SHOPS TO PURCHASE SUPPLIES, HEAL\l"
	.string "YOUR POKEMON, AND OTHER BENEFITS.\p"
	.string "ONCE YOU ENTER A NEW ZONE,\n"
	.string "YOU WILL NOT BE ABLE TO RETURN TO\l"
	.string "THE SHOP AREA, NOR ANY PRIOR ZONES.$"

gText_Quentin_DontLose:
	.string "{COLOR BLUE}QUENTIN{COLOR DARK_GREY}: YOU MUST PROGRESS THROUGH\n"
	.string "ALL ZONES WITHOUT LOSING A BATTLE,\l"
	.string "WHICH WOULD RESULT IN AN AUTOMATIC\l"
	.string "RESTART OF THE SIMULATION.$"


gText_Joy_Welcome:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: Welcome to Joy's Healing Shop.\p"
	.string "We heal your Pokemon for a flat\n"
	.string "¥500 fee, which also comes with\l"
	.string "access to the PC.$"

gText_Joy_Nuzlocke:
	.string "I will also remove any fallen\n"
	.string "Pokémon in your party.$"

gText_Joy_WouldYouLikeToHeal:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: Should I heal your Pokémon?$"

gText_Joy_NotEnough:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: You don't have enough money.$"

gText_Joy_ThankYou:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: That will be ¥500, thank you…$"

gText_Joy_PartyHealed:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: Your party has been restored.\n"
	.string "You can also now use the PC.$"

gText_Joy_WonderfulDay:
	.string "{COLOR BLUE}Joy{COLOR DARK_GREY}: Have a wonderful day!$"

gText_Quentin_Onwards:
	.string "{COLOR BLUE}QUENTIN{COLOR DARK_GREY}: ONWARDS, TO VICTORY!$"

gText_GeneralSign:
	.string "Tim's General Purpose Shop\n"
	.string "Sponsored by Pokémart Inc.$"

gText_Tim_Welcome:
	.string "{COLOR BLUE}Tim{COLOR DARK_GREY}: Welcome to Tim's.\n"
	.string "Can I get you anything?$"

gText_Tim_Leave:
	.string "{COLOR BLUE}Tim{COLOR DARK_GREY}: Have a nice day.$"

gText_ItemSign:
	.string "Silph Unique Item Shop\n"
	.string "Need something? We probably got it!$"

gText_Varrick_Welcome:
	.string "{COLOR BLUE}Varrick{COLOR DARK_GREY}: Greetings and salutations!\n"
	.string "Welcome to Silph Unique Item Store!$"

gText_Varrick_Leave:
	.string "{COLOR BLUE}Varrick{COLOR DARK_GREY}: A big thank you from Silph!$"

gText_ServicesSign:
	.string "Lelouch's Special Services Shop\n"
	.string "Anything for the right price...$"

gText_HealingSign:
	.string "Joy's Healing Shop\n"
	.string "Health care costs money!$"

