gText_Birch_Welcome:: @ 82C897B
	.string "Hello there!\p"
	.string "This is a prerecorded message from\n"
	.string "{COLOR BLUE}Professor Birch{COLOR DARK_GREY} of Hoenn.\p"
	.string "You are about to journey into the\n"
	.string "{COLOR RED}Battle Labyrinth{COLOR DARK_GREY}, a simulated\l"
	.string "environment designed to test your\l"
	.string "abilities as a Trainer.\p"
	.string "The rules are simple.\p"
	.string "You must clear all the Zones, by\n"
	.string "any means necessary, in order to\l"
	.string "complete the {COLOR RED}Battle Labyrinth{COLOR DARK_GREY}.\p"
	.string "$"

gText_Birch_Pokemon:: @ 82C89FB
	.string "This is {COLOR BLUE}Quentin{COLOR DARK_GREY}, my Porygon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech:: @ 82C8A1F
	.string "As the {COLOR RED}Battle Labyrinth{COLOR DARK_GREY} is a\n"
	.string "simulated environment, {COLOR BLUE}Quentin{COLOR DARK_GREY} here\l"
	.string "can access it from the real world.\p"
	.string "{COLOR BLUE}Quentin{COLOR DARK_GREY} will provide the details\n"
	.string "you need to achieve success.\p"
	.string "In addition, we also need some\n"
	.string "registration from you.\p"
	.string "$"

gText_Birch_AndYouAre:: @ 82C8BD0
	.string "It will be confidential.$"

gText_Birch_BoyOrGirl:: @ 82C8BDD
	.string "Please input your gender.$"

gText_Birch_WhatsYourName:: @ 82C8BFF
	.string "Please input your name.$"

gText_Birch_SoItsPlayer:: @ 82C8C1C
	.string "Your name is {PLAYER}{KUN}?$"

gText_Birch_YourePlayer:: @ 82C8C2A
	.string "Thank you very much.\p"
	.string "This rom hack is by eatthepear.\p"
	.string "Please check the documentation if\n"
	.string "you have any questions or issues.\p"
	.string "$"

gText_Birch_AreYouReady:: @ 82C8C7A
	.string "We hope you enjoy the\n"
	.string "{COLOR RED}Battle Labyrinth{COLOR DARK_GREY}.\p"
	.string "Please brace yourself and\n"
	.string "delight in the challenge.\p"
	.string "$"
