Text_PictureBookShelf:
	.string "There's a set of Pokémon picture books.$"

Text_BookShelf:
	.string "It's filled with all sorts of books.$"

Text_PokemonCenterBookShelf:
	.string "Pokémon magazines!\n"
	.string "Pokémon Pal…\p"
	.string "Pokémon Handbook…\n"
	.string "Adorable Pokémon…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf:
	.string "The shelves are filled with\n"
	.string "Pokémon merchandise…\p"
	.string "But they're covered in dust and\n"
	.string "cobwebs…$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
