gText_PkmnTransferredSomeonesPC:: @ 8273216
	.string "{STR_VAR_2} was transferred to\n"
	.string "Someone's PC.\p"
	.string "It was placed in \n"
	.string "Box “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPC:: @ 8273256
	.string "{STR_VAR_2} was transferred to\n"
	.string "Colress's PC.\p"
	.string "It was placed in \n"
	.string "Box “{STR_VAR_1}.”$"

gText_PkmnTransferredSomeonesPCBoxFull:: @ 8273296
	.string "Box “{STR_VAR_3}” on\n"
	.string "Someone's PC was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "Box “{STR_VAR_1}.”$"

gText_PkmnTransferredLanettesPCBoxFull:: @ 82732D9
	.string "Box “{STR_VAR_3}” on\n"
	.string "Colress's PC was full.\p"
	.string "{STR_VAR_2} was transferred to\n"
	.string "Box “{STR_VAR_1}.”$"

gText_NoMoreRoomForPokemon:: @ 827331C
	.string "There's no more room for Pokémon!\p"
	.string "The Pokémon Boxes are full and\n"
	.string "can't accept any more!$"

gText_NicknameThisPokemon:: @ 8273374
	.string "Do you want to give a nickname to\n"
	.string "this {STR_VAR_1}?$"

gText_WouldLikeSendToPC::
	.string "{COLOR WHITE}Add {STR_VAR_1} to your party and\n"
	.string "send a party member to the PC?$"
