Common_EventScript_SetGymTrainers:: @ 8271F43
	switch VAR_0x8008
	case 1, RustboroCity_Gym_SetGymTrainers
	case 2, DewfordTown_Gym_SetGymTrainers
	case 3, MauvilleCity_Gym_SetGymTrainers
	case 4, LavaridgeTown_Gym_SetGymTrainers
	case 5, PetalburgCity_Gym_SetGymTrainers
	case 6, FortreeCity_Gym_SetGymTrainers
	case 7, MossdeepCity_Gym_SetGymTrainers
	case 8, SootopolisCity_Gym_SetGymTrainers
	end

RustboroCity_Gym_SetGymTrainers:: @ 8271FA1
	return

DewfordTown_Gym_SetGymTrainers:: @ 8271FAB
	return

MauvilleCity_Gym_SetGymTrainers:: @ 8271FBE
	return

LavaridgeTown_Gym_SetGymTrainers:: @ 8271FCE
	return

PetalburgCity_Gym_SetGymTrainers:: @ 8271FE7
	return

FortreeCity_Gym_SetGymTrainers:: @ 8271FFD
	return

MossdeepCity_Gym_SetGymTrainers:: @ 8272010
	return

SootopolisCity_Gym_SetGymTrainers:: @ 8272035
	return
